# -*- coding: utf-8 -*-
"""Hash_02. 완주하지 못한 선수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ed-kR6rSwNTHmRzhJNlm7SsTIrJwO6Xt
"""

def solution(p, c):
    if len(set(p)) != len(set(c)):
        return ''.join((set(p)- set(c)))
    
    else:
        for i in c:
            if c.count(i) != p.count(i):
                return i