# -*- coding: utf-8 -*-
"""Hash_01. 폰켓몬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WmXtgk4eAmVm7UT3PZYsziLRktvAl9IC
"""

def solutions(nums):
    answer = 0
    num = int(len(nums)/2)
    arr = list(set(nums))

    if len(arr) > num:
        answer = num
    else:
        answer = len(arr)
    return answer

"""### 충격"""

def solution(ls):
    return min(len(ls)/2, len(set(ls)))