SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS a
INNER JOIN ICECREAM_INFO AS b
ON a.FLAVOR = b.FLAVOR
GROUP BY b.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;

-- 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량 조회 : SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER
-- 총주문량이 작은 순서대로 조회 : ORDER BY TOTAL_ORDER ASC
-- 총주문량을 나타내는 컬럼명은 TOTAL_ORDER로 지정 : SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER