SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY;

-- PRODUCT_CODE 왼쪽에서부터 2번째까지를 기준으로 선택하고 이를 CATEGORY라고 칭함
-- PRODUCT_ID를 COUNT하고 PRODUCTS라고 칭함 이때 CATEGORY 기준으로 묶기