# -*- coding: utf-8 -*-
"""Sort_01. K번째 수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13iF48qxLcZl4YifoelkEvyzT5zhrSyuD
"""

def solution(array, commands):
    a = []
    for i in range(len(commands)):
        s_array =  sorted(array[commands[i][0]-1:commands[i][1]])
        a.append(s_array[commands[i][2]-1])
    return a