SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE') AS TLNO
FROM PATIENT
WHERE GEND_CD = 'W'
AND AGE BETWEEN 0 AND 12
ORDER BY AGE DESC, PT_NAME;

-- IFNULL(테이블명, 'NULL일때 나타낼 값') AS 컬럼명
-- ORDER BY 정렬조건1, 정렬조건2, 정렬조건 3