SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;

-- 재구매 기준 점검하기
-- GROUP BY로 사용자ID별 상품ID를 묶어줌
-- 이때 COUNT를 통해 2개 이상일 경우 재구매 TRUE