SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt' AND CART_ID 
IN( SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk')
ORDER BY CART_ID

-- 다른 풀이(교집합 이용)
SELECT A.CART_ID
FROM
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'MilK') AS A JOIN
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') AS B
WHERE A.CART_ID = B.CART_ID
ORDER BY CART_ID

-- 다른 풀이(셀프 조인: 위와 비슷함)
SELECT A.CART_ID
FROM CART_PRODUCTS AS A JOIN CART_PRODUCTS AS B
ON A.CART_ID = B.CART_ID
WHERE A.NAME = 'Milk' AND B.NAME = 'Yogurt'
ORDER BY A.CART_ID

-- 출처: https://se-jung-h.tistory.com/entry/SQLMYSQL-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%9A%B0%EC%9C%A0%EC%99%80-%EC%9A%94%EA%B1%B0%ED%8A%B8%EA%B0%80-%EB%8B%B4%EA%B8%B4-%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88